# ⚠️ هذا الرابط يجب أن يكون دقيقاً جداً وينتهي بـ Slash /
baseURL = "https://knowledgehubs.github.io/my-menu-project/"
languageCode = "en-us"
title = "Digital Menu Engine"

# لتصحيح مسارات الروابط داخل مجلد المشروع
canonifyURLs = true

[server]
  disableFastRender = true

[markup.goldmark.renderer]
  unsafe = true
